[package]
name = "raft_db_sql"
version.workspace = true
edition.workspace = true

[dependencies]
raft_db_common = { workspace = true }

dyn-clone = { workspace = true }
serde = { workspace = true }
itertools = { workspace = true }